CREATE TABLE admin (
    id SERIAL NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    username text NOT NULL,
    password_hash text NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX admin_username_key ON public.admin USING btree (username);


-- Generated by the database client.
CREATE TABLE clients (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    cpf varchar(14),
    instagram varchar(100),
    phone varchar(20),
    zip_code varchar(10),
    address text,
    reference_point text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX unique_cpf ON public.clients USING btree (cpf);


-- Generated by the database client.
CREATE TABLE clothings (
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    price numeric(10, 2) NOT NULL,
    queue_name varchar(255),
    purchase_channel varchar(50),
    purchase_type varchar(50),
    discount numeric(10, 2) DEFAULT 0,
    total_price numeric,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- Generated by the database client.
CREATE TABLE mining (
    id SERIAL NOT NULL,
    quantity integer NOT NULL,
    total_value numeric(10, 2) NOT NULL,
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- Generated by the database client.
CREATE TABLE payment_method (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    name varchar(255),
    active boolean DEFAULT false,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX unique_payment_method_name ON public.payment_method USING btree (name);

-- Generated by the database client.
CREATE TABLE pix_keys (
    id SERIAL NOT NULL,
    payment_method_id integer,
    "key" varchar(255) NOT NULL,
    "type" varchar(50) NOT NULL,
    receptor_name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    active boolean DEFAULT true,
    main boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT pix_keys_payment_method_id_fkey FOREIGN key (payment_method_id) REFERENCES payment_method (id),
    CONSTRAINT pix_keys_type_check CHECK (
        (
            (type)::text = ANY (
                (
                    ARRAY[
                        'CPF'::character varying,
                        'CNPJ'::character varying,
                        'EMAIL'::character varying,
                        'TELEFONE'::character varying,
                        'ALEATORIA'::character varying
                    ]
                )::text []
            )
        )
    )
);

CREATE UNIQUE INDEX pix_keys_key_key ON public.pix_keys USING btree (key);

CREATE INDEX idx_pix_keys_payment_method ON public.pix_keys USING btree (payment_method_id);

CREATE INDEX idx_pix_keys_active ON public.pix_keys USING btree (active);

CREATE INDEX idx_pix_keys_main ON public.pix_keys USING btree (main);

-- Generated by the database client.
CREATE TABLE pix_keys (
    id SERIAL NOT NULL,
    payment_method_id integer,
    "key" varchar(255) NOT NULL,
    "type" varchar(50) NOT NULL,
    receptor_name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    active boolean DEFAULT true,
    main boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT pix_keys_payment_method_id_fkey FOREIGN key (payment_method_id) REFERENCES payment_method (id),
    CONSTRAINT pix_keys_type_check CHECK (
        (
            (type)::text = ANY (
                (
                    ARRAY[
                        'CPF'::character varying,
                        'CNPJ'::character varying,
                        'EMAIL'::character varying,
                        'TELEFONE'::character varying,
                        'ALEATORIA'::character varying
                    ]
                )::text []
            )
        )
    )
);

CREATE UNIQUE INDEX pix_keys_key_key ON public.pix_keys USING btree (key);

CREATE INDEX idx_pix_keys_payment_method ON public.pix_keys USING btree (payment_method_id);

CREATE INDEX idx_pix_keys_active ON public.pix_keys USING btree (active);

CREATE INDEX idx_pix_keys_main ON public.pix_keys USING btree (main);

-- Generated by the database client.
CREATE TABLE purchase_clothings (
    purchase_id integer,
    clothing_id integer,
    CONSTRAINT compra_pecas_compra_id_fkey FOREIGN key (purchase_id) REFERENCES purchases (id),
    CONSTRAINT compra_pecas_peca_id_fkey FOREIGN key (clothing_id) REFERENCES clothings (id)
);

-- Generated by the database client.
CREATE TABLE purchases (
    id SERIAL NOT NULL,
    client_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_paid boolean DEFAULT false,
    is_delivery_asked boolean DEFAULT false,
    is_delivery_sent boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    tracking_code varchar(255) DEFAULT NULL::character varying,
    payment_method_name text,
    PRIMARY KEY (id),
    CONSTRAINT compras_cliente_id_fkey FOREIGN key (client_id) REFERENCES clients (id),
    CONSTRAINT fk_payment_method_name FOREIGN key (payment_method_name) REFERENCES payment_method (name)
);
